### ISSUE TITLE
InfCloud Web Interface Not launching

### ISSUE THREAD

**Issue by kirkzp** [Unrud/RadicaleInfCloud#14]
Hi,
I am running Radicale 3.0.
I added RadicaleInfCloud from the tar
I edited the radicale config to add 
[web]
type = radicale_infcloud

When I run radicale with --debug flag, I get notification that:
"web type is 'radicale_infcloud' " notification, so I believe that my radicale knows it should use infcloud interface.

But, when I navigate a browser to my radicale service (e.g., localhost:5232) the normal radicale interface comes up instead of infcloud.

I tried clearing my html5 cache b/c I thought it might just not be reloading the page.  But, that didn't work.  So,
1. Are there some diagnostic tests I could run?
2. Is there something the radicale_infcloud config.js that I need to set?
Thanks!
Kirk

**Comment by Unrud** [comment]
http://localhost:5232/.web/infcloud

**Comment by kirkzp** [comment]
Dear Unrud,
Thank your for your quick response.  I have added that exact line to my config.js.  Now it appears that infcloud is running--but I am still not getting a proper infcloud interace.  I am getting the usual radicale-server interface, albeit with the word "InfCloud" added up top.

I am attaching 3 photos. 
1) my current login screen
2) page I land on after a valid log-in
3) SEPARATELY, a pic from the infcloud web demo page. that show infcloud calendar after loading collections for the (valid) current user.
Any thoughts on why I am seeing #2 (radicale interface) instead of something like #3?  
Note: Radicale is working and I have created and populated test calendars from an Android Device using DavX^5 and from Windows Outlook with CalDAV plug-in.
Thanks again,  Kirk

**Comment by kirkzp** [comment]
![LogIn](https://user-images.githubusercontent.com/66496505/94728088-8cb78a00-0314-11eb-8040-fee1a275aef3.png)
![InfTwo](https://user-images.githubusercontent.com/66496505/94728093-8e814d80-0314-11eb-89aa-9b6b60794d9d.png)
![InfCal](https://user-images.githubusercontent.com/66496505/94728106-9214d480-0314-11eb-99bc-bdf0f5b63535.png)

**Comment by kirkzp** [comment]
Hi, sorry for the verbosity.  I am trying to figure this out myself and thereby save you from having to help.  But, I am unable.  Here's what seems to be a sequence/problem:
1. I go to localhost:5232, which successfully brings up the radicale interface (with 'InfCloud' link)
2. I log in as 'test' 
3. Screen changes to radicale web interface showing the resources (calendars and addressbooks) available to 'test'
4. I click on the "InfCloud" link
5. I get whitescreen that hangs indefinitely.
6. I have done this with --debug option for radicale.  The basics work (I can see that login happens and I can see that the list of resources for 'test' is correct).  Where things breakdown/hang is when there is a request made to get "/favicon.ico".  This returns a message "Access to '/favicon.ico' denied for 'test' "
with follow-ups of "Access to the requested resource forbidden" and "403 Forbidden".

I have no idea why this is happening.  I did a 'find' to locate 'favicon.ico' and there are several instances in /usr/lib and /usr/share but those seem to be associated with *other* programs (libreoffice, scratch2).  I am GUESSING that the issue is not authorization to the .ico but rather that it doesn't exist and this is the web server error msg for that???  Are there perhaps some icons, or other resources, needed for infcloud for radicale that did not get installed when I pip installed the master tar.

I am attaching some of the debug output---in case it helps.  

Thanks for any direction you can provide.

**Comment by kirkzp** [comment]
[Short Debug.txt](https://github.com/Unrud/RadicaleInfCloud/files/5308710/Short.Debug.txt)

**Comment by kirkzp** [comment]
OK.  I have made some progress.  I now get the infcloud log-in screen when I click the link.  And,
1) if I enter an invalid username+pw I get the other server login popup (which cannot be avoided)
2) if I enter a valid username+pw, I do NOT get that.  But, after some cycling, nothing happens.  
Looking at debug and/or web-session console log, I see that:
**Access to '/.web/infcloud/' denied for 'test'** (debug)
and
Error 403 access to resource denied (web-client console).

I am wondering if the InfCloud client is trying to read or write to some directories that the radicale server/linux user does not have access to?   

Strange because radicale web interface works fine:  I can add users; add calendars; add addressbooks; etc.  and I can sync with the radicale server from other devices/calDAV clients.

InfCloud was installed with the same ownership and permissions as radicale server, so it shouldn't be trying to access anything that the radicale user/server can't access...but perhaps it is?

Any ideas?

Thanks!!! Kirk

**Comment by kirkzp** [comment]
I have tried seemingly every possible permutation of things, and I still find no success.  Radicale works fine.  When I visit the Radicale web interface and click on "InfCloud" I am taken to the InfCloud login screen--this is true whether I am on the box running radicale or a different machine on the LAN.

However, I can never successfully login and access resources from InfCloud page.  I have played extensively with both radicale's config file and infcloud's config.js.

In particular, I have added these header lines to the radicale config file:


Access-Control-Allow-Origin = *
Access-Control-Allow-Methods = GET, POST, OPTIONS, PROPFIND, PROPPATCH, REPORT, PUT, MOVE, DELETE, LOCK, UNLOCK
Access-Control-Allow-Headers = User-Agent, Authorization, Content-type, Depth, If-match, If-None-Match, Lock-Token, Timeout, Destination, Overwrite, Prefer, X-client, X-Requested-With
Access-Control-Expose-Headers = Etag, Preference-Applied

It is claimed that these will enable the InfCloud client to access radicale resources.  But, I keep getting connection-refused errors as shown in the attached screenshot.

Does anyone have any idea what additional configuration I need to do?  I have played with having a "/" or not having a "/" after my href setting.  I have messed around with using "localhost" vs. "127.0.0.1" vs. my fixed LAN IP.  I have tried using all 3 infcloud access modes.  Nothng works.  Nada. Zilch. Riente. Bubkis :(

Help appreciated--including appreciation shown via coffee or beer donations :)

Thanks much.  

![Web_Console](https://user-images.githubusercontent.com/66496505/94979179-35611780-04d6-11eb-9494-57b5e9b42c3d.jpg)

**Comment by Unrud** [comment]
>  I have played with having a "/" or not having a "/" after my href setting.

The `href` settings are wrong. InfCloud tries to access `http://127.0.0.1:5232/.web/infcloud` but it should be `http://127.0.0.1:5232/`. 

> I have played extensively with both radicale's config file and infcloud's config.js.

It should work out-of-the-box. Touching `config.js` should not be necessary.

> In particular, I have added these header lines to the radicale config file:

This is only necessary when InfCloud is not running on the same server/host. No changes should be required here.

**Comment by kirkzp** [comment]
Hi,
I guess I mis-understood your previous comment (above) that [seemed!] to say to me that I needed the full "http://localhost:5232/.web/infcloud" as my href.  

I returned to the out-of-the-box config.js and got things working (I think...fingers crossed).

Thanks for your help!  Great contribution.

Kirk

**Comment by kirkzp** [comment]
Hey, was gonna donate a cup of coffee.  Do you have a PayPal contribution link?  -Kirk
