### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by decentropy** [Unrud/RadicaleInfCloud#24]
Sorry - maybe a dumb question, but how do I run this?

I have radicale installed already.
Then I ran: python3 -m pip install --upgrade https://github.com/Unrud/RadicaleInfCloud/archive/master.tar.gz

What now?

**Comment by decentropy** [comment]
Ok, my bad... 
Realized this is an integration, not separate app.

I edited the radicale config with [web] section, then restarted... 
I get a blank screen, but that's a separate issue - so closing

**Comment by tmst** [comment]
Decentropy - greatest username ever!
