### ISSUE TITLE
Loading resources

### ISSUE THREAD

**Issue by dymn** [Unrud/RadicaleInfCloud#3]
Hi again!
RadicaleInfCloud and Radicale installed on the localhost.

When i trying to login into InfCloud (http://127.0.0.1:5232/.web/infcloud/) i got endless "Loading resources (1 of 1)" spinner.

In the FF console i got next error:
TypeError: tmp is null[Подробнее]  resource.js:302:3
	ResourceCalDAVList/this.getSortKey http://127.0.0.1:5232/.web/infcloud/resource.js:302:3
	ResourceCalDAVList/this.insertResource http://127.0.0.1:5232/.web/infcloud/resource.js:314:25
	ajaxComplete/</< http://127.0.0.1:5232/.web/infcloud/webdav_protocol.js:1614:8
	each http://127.0.0.1:5232/.web/infcloud/lib/jquery-2.1.4.min.js:2:2880
	each http://127.0.0.1:5232/.web/infcloud/lib/jquery-2.1.4.min.js:2:845
	ajaxComplete/< http://127.0.0.1:5232/.web/infcloud/webdav_protocol.js:1448:4
	each http://127.0.0.1:5232/.web/infcloud/lib/jquery-2.1.4.min.js:2:2880
	each http://127.0.0.1:5232/.web/infcloud/lib/jquery-2.1.4.min.js:2:845
	ajaxComplete http://127.0.0.1:5232/.web/infcloud/webdav_protocol.js:1447:3
	j http://127.0.0.1:5232/.web/infcloud/lib/jquery-2.1.4.min.js:2:26920
	fireWith http://127.0.0.1:5232/.web/infcloud/lib/jquery-2.1.4.min.js:2:27738
	x http://127.0.0.1:5232/.web/infcloud/lib/jquery-2.1.4.min.js:4:11251
	b/< http://127.0.0.1:5232/.web/infcloud/lib/jquery-2.1.4.min.js:4:14765

What the reason?

**Comment by Unrud** [comment]
Does InfCloud work a new user with an empty calendar?

It's possible that InfCloud doesn't like one of the existing events of the calendar. Unfortunately InfCloud has some bugs and the project seems dead.

**Comment by dymn** [comment]
With a new user with an empty calendar all is ok.
Hmm, how can i find this events of the calendar?
