### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by typhoon71** [Unrud/RadicaleInfCloud#7]
I'm experiencing a problem installing this on a synology NAS.

On my ubuntu server I just do:
"python3 -m pip install --upgrade git+https://github.com/Unrud/RadicaleInfCloud"
and after enabling it in Radicale's config file it works fine.

On the Synology NAS there's no git command available, and no cli package management, so I tried doing this:

wget https://github.com/Unrud/RadicaleInfCloud/archive/master.zip
unzip master.zip
cd RadicaleInfCloud-master/
python3 setup.py install

The setup completes with no errors but if I browse to system the python folder (the Synology equivalent of "/usr/local/lib/python3.5/dist-packages" on ubuntu) there's no "radicale_infcloud" nor "Radicale_InfCloud-2.0.0.egg-info", the 2 folders I see on ubuntu. 
There's only a Radicale_InfCloud-2.0.0 -something- .egg file: I tried to install the .eggusing easy_install but while I get no errors during the setup there's no changes at all.

I'm pretty sure pip works on the Synology, since I installed Radicale with it and it's working fine.

Can someone give me some pointers as why the setup doesn't install the incloud radicale webui?
I think it doesn't get installed because the page I see at IP:5232 is the same as the internal Radicale setup, without the link to the infcloud one.

I would be fine even with steps to manually copy the relevant files in place, whatever is easier to do for you, but I'd like to understand why the setup is failing too.

Thanks in advance.

**Comment by ayevee** [comment]
@typhoon71 install "Git Server" package from Synology package center. It will give you all necessary CLI commands. Works for me that way (Radicale + Radicale Inf Cloud + Radicale IMAP auth).

P.S. and you will be able to use git for versioning Radicale data as well.

**Comment by Unrud** [comment]
> I think it doesn't get installed because the page I see at IP:5232 is the same as the internal Radicale setup, without the link to the infcloud one.

Did you add
```ini
[web]
type = radicale_infcloud
```
to Radicale's configuration?

If ``radicale_infcloud`` is configured and it is not installed, Radicale shouldn't even start.

**Comment by typhoon71** [comment]
@ayevee
I didn't think of that since it says "server"... whatever, I tried, same issue.
Since you seem to have Radicale working on Synology: does it synch on android too? 
It doesn't here: while DAV is enabled in apache's config (vhost) it still doesn't allow PROPFIND.
Puzzling. If I could make this work I'd be really happy... 

@Unrud
I did add type = radicale_infcloud ine the [web] section of the config file, commenting the other option there.
Anyway, I needed to test Radicale so I used the internal webui and added a valid contact ... manually, but I'd like to know why this happens.

**Comment by Unrud** [comment]
> I did add type = radicale_infcloud ine the [web] section of the config file, commenting the other option there.

And Radicale did start? That's strange.

Can you start Radicale with the ``--debug`` argument and check if it prints:

```
[xxx] INFO: Web type is 'radicale_infcloud'
```

**Comment by ayevee** [comment]
@typhoon71 
Yes I have Radicale running on Synology NAS and it is successfully syncing with android, windows 10 and MS Outlook for me.

Here is my step by step set-up process:

- Install Git Server and Python3 packages
- Create radicale user, group, shared folder. Assign permissions.
- In `control panel -> application portal -> reverse proxy` create a new rule with http://localhost:5232 destination (optional)
- `sudo python3.5 -m ensurepip`
- `sudo python3.5 -m pip install --upgrade pip`
- `sudo python3.5 -m pip install --upgrade radicale`
- `sudo python3.5 -m pip install --upgrade git+https://github.com/ayevee/RadicaleInfCloud` (forked this repo to apply my configuration)
- `sudo python3.5 -m pip install --upgrade git+https://github.com/ayevee/radicale_imap_auth` (to use IMAP auth, @Unrud has a repo with IMAP auth implementation as well)
- `sudo mkdir /run/radicale`
- `sudo chown -R radicale:radicale /run/radicale`
- `sudo mkdir /etc/radicale`
- `sudo chown -R radicale:radicale /etc/radicale`
- `sudo -u radicale vim /etc/radicale/config`
- `sudo -u radicale vim /etc/radicale/logconfig`

Obviously your user/group name and paths may be different

To start Radicale manually run `sudo -u radicale /usr/local/bin/python3.5 -m radicale`, for autostart put the same command into bootup Scheduled Task

N.B. You have to set up everything from scratch after you install Pyhton3 package upgrade.

**Comment by typhoon71** [comment]
@ayevee
Thanks a lot for your info.
My setup sequence was a bit different.
Also, the Synology I'm using is running everything as root, which makes me irk... (DSM5 I think)

Anyway the things I did differently are:
- I didn't install git (maybe that can fix the infcloud issue, but it's not that important) 
- I made the upstart file myself, that works perfectly even upon reboot, didn't use scheduled task
- I made the reverse provy manually, not using the webUI (while it works for Thunderbird + Lightning it could be related to Android not working, those config files are messy)

As soon I can get some spare time I'll see how Android clients behave on a plain ubuntu setup, since when I saw Thunderbird + Lightning working there I just hopped on the Synology... 
Does your setup works for Android clients? Both abooks and calendars?

**Comment by ayevee** [comment]
@typhoon71 
My NAS is running DSM 6.1 so I don't think I'll be able to provide any help with an older OS version.

My setup works for android clients (with davdroid) for addressbooks, calendar and tasks.

**Comment by typhoon71** [comment]
Oh, so you're on DSM6. Well, there's a planned update to it, so it's not like everything is lost.
I'm using davdroid too (also tried cardavmate), so knowing it can work is already good.
I'm pretty sure the issue is in the rev proxy, but I'll check that in the weekend.
I'll close the topic since it's starti ng to become out of place here, since it became unrelated to radicale infcloud...

**Comment by typhoon71** [comment]
@ayevee 
If it's not asking too much, could you port your proxy config for radicale?
Right now I'm successful running it on a ubuntu box, connecting to it with both thunderbird and android (DavDroid OSE).
While your OS is different from mine, I'm sure I can learn from it enough to have this running.
the thing I'm interested a lot is if you're proxying using nginx or apache, since I read DSM6 id going full ngnix. 
It's a bit of a shame Radicale Documentation doesn't have an example for Apache, I think my setup is correct, but I have nothing to compare it to.
Thanks for any help.
